<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="HijraMobile"
           tests="4"
           failures="1"
           errors="0"
           skipped="0"
           time="58.213">
    <properties></properties>

            <testcase
                name="transferHijra"
                time="26.721"
                classname="test.Transaction.TransferToHijra">

            <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
                org.testng.Assert.fail(Assert.java:94)org.testng.Assert.failNotEquals(Assert.java:513)org.testng.Assert.assertTrue(Assert.java:42)org.testng.Assert.assertTrue(Assert.java:52)controller.Transaction.TransferHijraController.validationDetailRekPenerima(TransferHijraController.java:84)test.Transaction.TransferToHijra.transferHijra(TransferToHijra.java:70)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:564)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)org.testng.internal.Invoker.invokeMethod(Invoker.java:645)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)org.testng.TestRunner.privateRun(TestRunner.java:756)org.testng.TestRunner.run(TestRunner.java:610)org.testng.SuiteRunner.runTest(SuiteRunner.java:387)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)org.testng.SuiteRunner.run(SuiteRunner.java:289)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)org.testng.TestNG.runSuitesLocally(TestNG.java:1218)org.testng.TestNG.runSuites(TestNG.java:1133)org.testng.TestNG.run(TestNG.java:1104)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </failure>
    </testcase>


            <testcase
                name="loginValid"
                time="15.937"
                classname="test.Transaction.TransferToHijra">
            </testcase>
            <testcase
                name="startActivityBahasa"
                time="12.181"
                classname="test.Transaction.TransferToHijra">
            </testcase>
            <testcase
                name="skipCarousel"
                time="3.374"
                classname="test.Transaction.TransferToHijra">
            </testcase>
</testsuite>
